/* Waffle House Phase 4A/4B/4D/4E · build 2026.08.28.01 */
(function(){
'use strict';
if(window.WAFFLE_PHASE4_BOOKING)return;
function C(){return window.WAFFLE_PHASE4_CORE}
function $ (id){return document.getElementById(id)}
const SOURCES=['Pawshake','Mad Paws','Referral','Direct','Other'];
let shotUrl='',observer=null;
function bookingHtml(){return `<div class="p4-section"><h3>Fast Booking Intake</h3><p>Paste an enquiry or attach a booking screenshot. Waffle prepares the details for review before anything is saved.</p><label class="p4-field"><span>Marketplace message</span><textarea id="p4Paste" placeholder="Paste the owner’s message here…"></textarea></label><div class="p4-screenshot"><label class="p4-field"><span>Booking screenshot</span><input id="p4Screenshot" type="file" accept="image/*"></label><img id="p4ScreenshotPreview" alt="Booking screenshot preview" hidden><small>Automatic screenshot text extraction uses your browser’s on-device text detector when available. Otherwise attach the screenshot for reference and paste the message text.</small></div><div class="p4-actions"><button class="primary" id="p4ParseBooking" type="button">✨ Parse Booking</button></div></div><div class="p4-section"><div class="p4-grid"><label class="p4-field"><span>Source</span><select id="p4Source">${SOURCES.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="p4-field"><span>Dog</span><input id="p4Dog"></label><label class="p4-field"><span>Breed</span><input id="p4Breed"></label><label class="p4-field"><span>Owner</span><input id="p4Owner"></label><label class="p4-field"><span>Phone</span><input id="p4Phone" inputmode="tel"></label><span></span><label class="p4-field"><span>Start</span><input id="p4Start" type="date"></label><label class="p4-field"><span>End</span><input id="p4End" type="date"></label><label class="p4-field wide"><span>Notes / original enquiry</span><textarea id="p4Notes"></textarea></label></div><div id="p4Duplicate" class="p4-warning" hidden></div><div id="p4ReturningMini"></div><div id="p4BookingDecision"></div><div class="p4-actions"><button id="p4SavePotential" type="button">❓ Save Potential</button><button class="primary" id="p4SaveConfirmed" type="button">🏡 Create Confirmed Stay</button></div></div>`}
function capacityHtml(){const s=C().settings();return `<div class="p4-section"><h3>Can I take this dog?</h3><p>Advisory check using confirmed boardings only. Potential stays and Meet &amp; Greets do not consume capacity.</p><div class="p4-grid"><label class="p4-field"><span>Dog / label</span><input id="p4CapDog"></label><label class="p4-field"><span>Dogs in request</span><input id="p4CapCount" type="number" min="1" value="1"></label><label class="p4-field"><span>Start</span><input id="p4CapStart" type="date"></label><label class="p4-field"><span>End</span><input id="p4CapEnd" type="date"></label><label class="p4-field"><span>Preferred maximum</span><input id="p4Pref" type="number" min="1" value="${s.preferred}"></label><label class="p4-field"><span>Absolute maximum</span><input id="p4Abs" type="number" min="1" value="${s.absolute}"></label></div><div class="p4-actions"><button class="primary" id="p4CapCheck" type="button">Check Capacity</button></div><div id="p4CapResult"></div></div>`}
function ownerHtml(){return `<div class="p4-section"><h3>Owner Self-Service & Returning Guest</h3><p>Create the existing secure Waffle care/intake link. Returning owners can confirm what changed instead of starting from scratch.</p><div class="p4-grid"><label class="p4-field"><span>Dog</span><input id="p4OwnerDog"></label><label class="p4-field"><span>Owner phone (optional match)</span><input id="p4OwnerPhone" inputmode="tel"></label><label class="p4-field"><span>Stay start</span><input id="p4OwnerStart" type="date"></label><label class="p4-field"><span>Stay end</span><input id="p4OwnerEnd" type="date"></label></div><div class="p4-actions"><button id="p4CheckReturn" type="button">🐾 Check Guest History</button><button class="primary" id="p4OwnerLink" type="button">🔗 Create / Copy Owner Care Link</button><button id="p4BookAgain" type="button">↻ Book Again</button></div><div id="p4Returning"></div><div id="p4LinkResult"></div></div>`}
function values(){return{source:$('p4Source')?.value||'Other',dogName:$('p4Dog')?.value.trim()||'',breed:$('p4Breed')?.value.trim()||'',ownerName:$('p4Owner')?.value.trim()||'',phone:$('p4Phone')?.value.trim()||'',startDate:$('p4Start')?.value||'',endDate:$('p4End')?.value||'',notes:$('p4Notes')?.value.trim()||''}}
function fill(v={}){for(const [id,key] of [['p4Source','source'],['p4Dog','dogName'],['p4Breed','breed'],['p4Owner','ownerName'],['p4Phone','phone'],['p4Start','startDate'],['p4End','endDate'],['p4Notes','notes']])if($(id)&&v[key]!=null)$(id).value=v[key];updateDecision()}
function validate(v,potential=false){if(!v.dogName)throw Error('Dog name is required.');if(!v.startDate||!v.endDate)throw Error('Start and end dates are required.');if(v.endDate<v.startDate)throw Error('End date cannot be before start date.');if(potential&&!v.ownerName)throw Error('Owner name is required for a Potential Stay.');if(potential&&!v.phone)throw Error('Contact number is required for a Potential Stay.')}
async function returning(dog,phone,hostId='p4Returning'){const host=$(hostId);if(!host)return null;if(!String(dog||'').trim()){host.innerHTML='<div class="p4-empty">Enter a dog name to check returning-guest history.</div>';return null}host.innerHTML='<div class="p4-empty">Checking guest history…</div>';const local=C().visits(dog);let remote=null;try{const r=await C().read({action:'get_returning_guest_prefill',dogName:dog,phone},{maxAttempts:1,timeoutMs:25000});remote=r?.prefill||null}catch(_){}const sug=remote?.suggested&&typeof remote.suggested==='object'?remote.suggested:(remote||{}),count=Math.max(local.length,Number(remote?.stayCount||sug.stayCount||0)),last=local[0]||null,matched=count>0||remote?.matched===true;if(!matched){host.innerHTML='<div class="p4-return"><strong>✨ New guest</strong><span>No previous confirmed stay found.</span></div>';return{matched:false,stayCount:0}}host.innerHTML=`<div class="p4-return"><strong>🐾 Returning guest · ${count} stay${count===1?'':'s'}</strong><span>${last?.endDate?`Last stay ended ${C().esc(C().fmt(last.endDate,true))}`:'Previous profile found'}</span>${hostId==='p4Returning'?`<span>Owner: ${C().esc(last?.ownerName||sug.ownerName||sug.owner||'Not stored')} · ${C().esc(last?.phone||sug.phone||'No contact')}</span>`:''}</div>`;return{matched:true,stayCount:count,last,sug}}
function updateDecision(){const v=values(),dup=v.dogName&&v.startDate&&v.endDate?C().duplicate(v.dogName,v.startDate,v.endDate):null,w=$('p4Duplicate');if(w){w.hidden=!dup;w.textContent=dup?`⚠️ Possible duplicate: ${dup.dogName} already has ${dup.bookingType} for ${C().fmt(dup.startDate)}–${C().fmt(dup.endDate)}.`:''}C().renderDecision(C().capacity(v.startDate,v.endDate,v.dogName),$('p4BookingDecision'));if(v.dogName)returning(v.dogName,v.phone,'p4ReturningMini').then(info=>{if(!info?.matched)return;const x=values(),r=info.last||info.sug||{};if(!x.breed&&r.breed)$('p4Breed').value=r.breed;if(!x.ownerName&&(r.ownerName||r.owner))$('p4Owner').value=r.ownerName||r.owner;if(!x.phone&&r.phone)$('p4Phone').value=r.phone}).catch(()=>{})}
async function parseShot(file){if(!file||!String(file.type||'').startsWith('image/'))throw Error('Choose a screenshot image first.');if(shotUrl)URL.revokeObjectURL(shotUrl);shotUrl=URL.createObjectURL(file);const img=$('p4ScreenshotPreview');img.src=shotUrl;img.hidden=false;if(typeof window.TextDetector!=='function'){C().toast('Screenshot attached. This browser cannot extract image text on-device; paste the message text below.','info');return''}const bitmap=await createImageBitmap(file);try{const blocks=await new window.TextDetector().detect(bitmap),text=(blocks||[]).map(b=>b.rawValue||b.text||'').filter(Boolean).join('\n');if(!text)throw Error('No readable text was detected.');return text}finally{bitmap.close?.()}}
async function save(kind){const v=values();validate(v,kind==='potential');const dup=C().duplicate(v.dogName,v.startDate,v.endDate);if(dup&&!confirm(`A matching ${dup.bookingType} already exists. Save another record anyway?`))return;const cap=C().capacity(v.startDate,v.endDate,v.dogName);if(cap?.band==='red'&&!confirm('This would exceed your absolute capacity setting. Continue anyway?'))return;const btn=$(kind==='potential'?'p4SavePotential':'p4SaveConfirmed'),old=btn.textContent;btn.disabled=true;btn.textContent='⏳ Saving…';try{const notes=[v.notes,v.source!=='Other'?`Source: ${v.source}`:''].filter(Boolean).join('\n');let r;if(kind==='potential')r=await C().write({action:'create_potential',id:'phase4_'+Date.now(),dogName:v.dogName,breed:v.breed||'N/A',startDate:v.startDate,endDate:v.endDate,ownerName:v.ownerName,phone:v.phone,notes,bookingType:'Potential Stay'});else r=await C().write({action:'create_boarding',dogName:v.dogName,breed:v.breed,startDate:v.startDate,endDate:v.endDate,ownerName:v.ownerName,phone:v.phone,notes,copyPreviousProfile:C().visits(v.dogName).length>0});C().toast(kind==='potential'?`✅ Potential stay saved for ${v.dogName}.`:`✅ ${v.dogName} confirmed.`,'success');if(r?.intake?.link)showLink(r.intake,v.dogName);window.dispatchEvent(new CustomEvent('waffle:phase4-data-changed'))}catch(e){C().toast('❌ '+(e.message||e),'error')}finally{btn.disabled=false;btn.textContent=old}}
function ownerValues(){return{dogName:$('p4OwnerDog')?.value.trim()||'',phone:$('p4OwnerPhone')?.value.trim()||'',startDate:$('p4OwnerStart')?.value||'',endDate:$('p4OwnerEnd')?.value||''}}
function showLink(intake,dog){const host=$('p4LinkResult');if(!host)return;const link=String(intake?.link||'');host.innerHTML=`<div class="p4-owner-card"><strong>✅ Owner care link ready for ${C().esc(dog||'guest')}</strong><span>For returning dogs, ask the owner to confirm what changed since the last stay.</span><input readonly value="${C().esc(link)}"><button type="button" data-p4-copy="${C().esc(link)}">Copy Link</button></div>`;host.querySelector('[data-p4-copy]')?.addEventListener('click',async e=>{const t=e.currentTarget.dataset.p4Copy;try{await navigator.clipboard.writeText(t);C().toast('Owner care link copied.','success')}catch(_){prompt('Copy owner care link:',t)}})}
async function createLink(){const v=ownerValues();validate({...v,ownerName:'',breed:''},false);const b=$('p4OwnerLink'),old=b.textContent;b.disabled=true;b.textContent='⏳ Creating…';try{const r=await C().write({action:'create_intake_link',dogName:v.dogName,startDate:v.startDate,endDate:v.endDate,intakeBaseUrl:typeof window.getExternalIntakeBaseUrl==='function'?window.getExternalIntakeBaseUrl():''});if(!r?.intake?.link)throw Error('The owner care link was not returned.');showLink(r.intake,v.dogName);await returning(v.dogName,v.phone)}catch(e){C().toast(e.message||String(e),'error')}finally{b.disabled=false;b.textContent=old}}
function fillOwner(row={}){$('p4OwnerDog').value=row.dogName||'';$('p4OwnerPhone').value=row.phone||'';$('p4OwnerStart').value=row.startDate||'';$('p4OwnerEnd').value=row.endDate||'';returning(row.dogName,row.phone)}
function bookAgain(){const v=ownerValues();if(!v.dogName)return C().toast('Enter a returning dog first.','info');const r=C().latest(v.dogName)||{};C().open('booking');fill({source:'Direct',dogName:v.dogName,breed:r.breed||'',ownerName:r.ownerName||'',phone:v.phone||r.phone||'',startDate:'',endDate:'',notes:'Returning guest — confirm what changed since the last stay.'});$('p4Start')?.focus()}
function runCap(){const s=C().saveSettings($('p4Pref').value,$('p4Abs').value);$('p4Pref').value=s.preferred;$('p4Abs').value=s.absolute;C().renderDecision(C().capacity($('p4CapStart').value,$('p4CapEnd').value,$('p4CapDog').value,$('p4CapCount').value),$('p4CapResult'))}
function cardData(card){const dog=String(card?.dataset?.directoryDogName||card?.dataset?.dogName||'').trim(),r=C().latest(dog)||{};return{dogName:dog,breed:String(card?.querySelector('[data-directory-edit-field="breed"]')?.dataset?.directoryCurrentValue||r.breed||''),ownerName:String(card?.querySelector('[data-directory-edit-field="ownerName"]')?.dataset?.directoryCurrentValue||r.ownerName||''),phone:String(card?.querySelector('[data-directory-edit-field="phone"]')?.dataset?.directoryCurrentValue||r.phone||''),startDate:String(card?.dataset?.directoryStartDate||r.startDate||''),endDate:String(card?.dataset?.directoryEndDate||r.endDate||'')}}
function enhanceCards(){if(C().page()!=='directory')return;document.querySelectorAll('.directory-card[data-directory-stay-key]').forEach(card=>{if(card.querySelector('.p4-directory-actions'))return;const d=cardData(card),count=C().visits(d.dogName).length,a=document.createElement('div');a.className='p4-directory-actions';a.innerHTML=`<button data-p4-dir="owner">🔗 Owner Care Link</button><button data-p4-dir="again">↻ Book Again</button>${count?`<button data-p4-dir="history">🐾 ${count} stay${count===1?'':'s'}</button>`:''}`;card.querySelector('.directory-card-header')?.insertAdjacentElement('afterend',a);a.onclick=e=>{const act=e.target.closest('[data-p4-dir]')?.dataset.p4Dir;if(!act)return;if(act==='again'){C().open('booking');fill({source:'Direct',dogName:d.dogName,breed:d.breed,ownerName:d.ownerName,phone:d.phone,startDate:'',endDate:'',notes:'Returning guest — confirm what changed since the last stay.'})}else{C().open('owner');fillOwner(d)}}})}
function wire(){const modal=C().modal();modal.querySelector('[data-p4-panel="booking"]').innerHTML=bookingHtml();modal.querySelector('[data-p4-panel="capacity"]').innerHTML=capacityHtml();modal.querySelector('[data-p4-panel="owner"]').innerHTML=ownerHtml();$('p4ParseBooking').onclick=()=>{const t=$('p4Paste').value;if(!t.trim())return C().toast('Paste an enquiry first.','info');fill(C().parseBooking(t));C().toast('Booking details prepared. Review before saving.','success')};$('p4Screenshot').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const t=await parseShot(f);if(t){$('p4Paste').value=t;fill(C().parseBooking(t));C().toast('Screenshot text extracted. Review before saving.','success')}}catch(err){C().toast(err.message||String(err),'error')}};for(const id of ['p4Dog','p4Phone','p4Start','p4End'])$(id).addEventListener('change',updateDecision);$('p4SavePotential').onclick=()=>save('potential');$('p4SaveConfirmed').onclick=()=>save('confirmed');$('p4CapCheck').onclick=runCap;$('p4CheckReturn').onclick=()=>{const v=ownerValues();returning(v.dogName,v.phone)};$('p4OwnerLink').onclick=createLink;$('p4BookAgain').onclick=bookAgain;if(C().page()==='directory'){const root=$('directory-grid')||document.body;observer=new MutationObserver(()=>setTimeout(enhanceCards,50));observer.observe(root,{childList:true,subtree:true});enhanceCards()}}
function start(){wire();[500,1800,4000].forEach(t=>setTimeout(enhanceCards,t))}
window.WAFFLE_PHASE4_BOOKING=Object.freeze({version:'2026.08.28.01',fill,fillOwner,returning,save,createOwnerCareLink:createLink,runCapacity:runCap,enhanceDirectory:enhanceCards});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
