const { test, expect } = require('@playwright/test');
const { resolveLocalBackendAction } = require('../scripts/local-network-policy');
const fs = require('node:fs');
const path = require('node:path');
const fullCalendar = fs.readFileSync(path.join(__dirname, 'fixtures', 'fullcalendar.global.min.js'), 'utf8');
const booking = { timestamp:'2026-09-18', dogName:'A very long dog name that wraps cleanly', breed:'Border Collie', startDate:'2026-09-17', endDate:'2026-09-22', ownerName:'Alexandria Peterson-Smith', phone:'0400123456', notes:'Safety warning remains visible.', bookingType:'Boarding', dogId:'11111111-1111-4111-8111-111111111111' };
async function fixture(page) {
  await page.route('**/*', async route => {
    const req=route.request(), url=req.url();
    if (!['GET','HEAD'].includes(req.method())) return route.fulfill({status:405,body:'Read-only fixture blocked mutation'});
    if (url.includes('docs.google.com/spreadsheets') && url.includes('output=csv')) { const row=[booking.timestamp,booking.dogName,booking.breed,'17/09/2026','22/09/2026',booking.ownerName,booking.phone,'','','','','Boarding','Other',booking.dogId,'#00017']; return route.fulfill({status:200,contentType:'text/csv',body:'Timestamp,Dog Name,Breed,Start Date,End Date,Owner,Phone,Likes,Dislikes,Notes,Edit Link,Booking Type,Source,Dog ID,Dog Number\n'+row.join(',')}); }
    if (url.includes('cdn.jsdelivr.net') && url.includes('fullcalendar')) return route.fulfill({status:200,contentType:'application/javascript',body:fullCalendar});
    if (url.includes('script.google')) { const resolved=resolveLocalBackendAction({method:req.method(),url}); if(!resolved.policy.allowed)return route.fulfill({status:403,body:'Read-only fixture blocked backend action'}); const q=new URL(url).searchParams, cb=q.get('callback'), p=JSON.parse(q.get('payload')||'{}'); let data={result:'success',records:[]}; if(resolved.action==='get_guest_directory')data={result:'success',bookings:[booking],summaries:[]}; if(resolved.action==='get_guest_profile')data={result:'success',record:{stayKey:p.stayKey,identity:{stayKey:p.stayKey,dogId:booking.dogId},resolution:{status:'resolved',method:'legacy-key-unique'},intakeAttributes:{},updatedAt:'2026-09-17T08:30:00.000Z',riskFlags:{}}}; return route.fulfill({status:200,contentType:'application/javascript',body:`${cb}(${JSON.stringify(data)});`}); }
    if (/^https?:/.test(url)&&new URL(url).hostname!=='127.0.0.1')return route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="4" height="4"></svg>'}); return route.continue();
  });
}
for (const [name,viewport,scheme] of [['320-light',{width:320,height:844},'light'],['320-dark',{width:320,height:844},'dark'],['390-light',{width:390,height:844},'light'],['390-dark',{width:390,height:844},'dark'],['540-light',{width:540,height:720},'light'],['540-dark',{width:540,height:720},'dark'],['1440-light',{width:1440,height:900},'light'],['1440-dark',{width:1440,height:900},'dark']]) test(`Booking tools readability and fit ${name}`,async({page,baseURL},info)=>{
  await page.setViewportSize(viewport); await page.emulateMedia({colorScheme:scheme}); await page.addInitScript(mode=>{localStorage.setItem('theme',mode);const N=Date,t=N.UTC(2026,8,18,12);function D(...a){if(!new.target)return new N(t).toString();return Reflect.construct(N,a.length?a:[t],new.target)}D.prototype=N.prototype;Object.setPrototypeOf(D,N);D.now=()=>t;globalThis.Date=D;},scheme); await fixture(page);
  await page.goto(`${baseURL}/directory.html?mobileHierarchy=1`,{waitUntil:'domcontentloaded'}); await page.waitForFunction(()=>document.documentElement.dataset.waffleUiReady==='true'); await expect.poll(()=>page.locator('.directory-card[data-directory-stay-key]').count()).toBe(1); await page.locator('[data-open-directory-profile]').evaluate(b=>b.click()); const profile=page.locator('.directory-card.is-profile-active'),tools=page.locator('.p4-directory-actions'); await expect(tools).toHaveCount(1); await expect(tools.locator('summary')).toBeVisible(); await tools.locator('summary').scrollIntoViewIfNeeded();
  const collapsed=await tools.evaluate(e=>({afterCareBrief:e.previousElementSibling?.matches('.directory-care-brief'),closed:!e.open,summary:(()=>{const b=e.querySelector('summary'),r=b.getBoundingClientRect();return{width:r.width,height:r.height,font:parseFloat(getComputedStyle(b).fontSize)}})()})); console.log(`BOOKING_TOOLS_COLLAPSED ${name} ${JSON.stringify(collapsed)}`); expect(collapsed.afterCareBrief).toBe(true); expect(collapsed.closed).toBe(true);
  await tools.locator('summary').focus(); await expect(tools.locator('summary')).toHaveCSS('outline-style','solid'); await page.keyboard.press('Enter'); await expect(tools).toHaveAttribute('open',''); const buttons=tools.locator('.p4-directory-action-list button[data-p4-dir]'); await expect.poll(() => buttons.count()).toBeGreaterThanOrEqual(2); await expect(buttons.first()).toBeVisible(); const sizes=await buttons.evaluateAll(bs=>bs.map(b=>{const r=b.getBoundingClientRect(),s=b.querySelector('small');return{label:b.querySelector('span').textContent.trim(),width:r.width,height:r.height,right:r.right,font:parseFloat(getComputedStyle(b).fontSize),helper:parseFloat(getComputedStyle(s).fontSize),helperScroll:s.scrollWidth,helperClient:s.clientWidth}})); console.log(`BOOKING_TOOLS_ACTIONS ${name} ${JSON.stringify(sizes)}`); expect(sizes.slice(0,2).map(x=>x.label)).toEqual(['Owner Care Link','Book Again']); expect(sizes.slice(0,2).every(x=>x.height>=44&&x.font>=13&&x.helper>=13&&x.right<=viewport.width+1&&x.helperScroll<=x.helperClient+1)).toBeTruthy(); const pointerGeometry=[]; for(const button of await buttons.all()){await button.scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))));pointerGeometry.push(await button.evaluate(b=>{const r=b.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,hit=document.elementFromPoint(x,y);return{label:b.textContent.trim(),target:hit?.closest('[data-p4-dir]')?.dataset.p4Dir||null,x,y}}))} console.log('BOOKING_TOOLS_POINTER',JSON.stringify(pointerGeometry)); expect(pointerGeometry.every(point=>point.target!==null),JSON.stringify(pointerGeometry)).toBeTruthy();
  const overflow=await page.evaluate(()=>({doc:document.documentElement.scrollWidth,view:document.documentElement.clientWidth,overlap:(()=>{const f=document.getElementById('wh75MobileBottomNav'),r=f?.getBoundingClientRect();return[...document.querySelectorAll('.p4-directory-action-list button')].some(b=>r?.height&&b.getBoundingClientRect().bottom>r.top&&b.getBoundingClientRect().top<r.bottom)})()})); expect(overflow.doc).toBeLessThanOrEqual(overflow.view+1); expect(overflow.overlap).toBe(false); await info.attach(`booking-tools-${name}`,{body:await page.screenshot({path:info.outputPath(`booking-tools-${name}.png`),fullPage:true}),contentType:'image/png'}); await buttons.first().click(); await expect(page.locator('#p4OwnerBookingContext')).toBeVisible();
});
