(() => {
  'use strict';
  const api = window.WaffleRndOps;
  if (!api) return;
  const { $, safeText, isoToday, humanDate, humanTime, statusLabel, activeBusiness, activeSettings, activeMembership, dogById } = api;

  function miniCard(stay, metaText) {
    const dog = dogById(stay.dog_id);
    const card = document.createElement('div'); card.className = 'ops-mini-card';
    const main = document.createElement('div');
    const strong = document.createElement('strong'); strong.textContent = dog?.dog_name || 'Unknown dog';
    const meta = document.createElement('span'); meta.textContent = metaText;
    main.append(strong, meta);
    const button = document.createElement('button'); button.type = 'button'; button.className = 'ghost'; button.textContent = 'Open'; button.dataset.editStay = stay.id;
    card.append(main, button); return card;
  }

  function renderToday(host) {
    host.innerHTML = `
      <section class="panel ops-hero"><div><p class="eyebrow">Today</p><h2 id="opsBusinessTitle"></h2><p id="opsTodayDate" class="ops-date"></p><p id="opsTenantMeta" class="muted"></p></div>
      <div class="ops-metrics"><article><strong id="opsAtHome">0</strong><span>At home</span></article><article><strong id="opsArriving">0</strong><span>Arriving</span></article><article><strong id="opsLeaving">0</strong><span>Leaving</span></article><article><strong id="opsMeetGreets">0</strong><span>Meet & Greets</span></article><article><strong id="opsCapacity">0</strong><span>Capacity</span></article></div></section>
      <section id="opsCapacityBanner" class="panel compact ops-capacity"></section>
      <div class="ops-today-grid"><section class="panel"><div class="split-heading"><div><p class="eyebrow">Care now</p><h3>Dogs at home</h3></div><button class="text-button" type="button" data-ops-jump="care">Open Care</button></div><div id="opsAtHomeEmpty" class="empty-state"><span class="empty-icon">🐾</span><strong>No dogs at home today</strong><p>Confirmed stays spanning today will appear here.</p></div><div id="opsAtHomeList" class="ops-card-list"></div></section>
      <section class="panel"><p class="eyebrow">Movements</p><h3>Arrivals & departures</h3><div id="opsMovesEmpty" class="empty-state"><span class="empty-icon">🚪</span><strong>No movements today</strong></div><div id="opsMovesList" class="ops-card-list"></div></section>
      <section class="panel"><p class="eyebrow">Appointments</p><h3>Meet & Greets</h3><div id="opsMeetEmpty" class="empty-state"><span class="empty-icon">🤝</span><strong>No Meet & Greets today</strong></div><div id="opsMeetList" class="ops-card-list"></div></section></div>`;

    const today = isoToday(); const business = activeBusiness();
    const confirmed = api.stays.filter(s => s.status === 'confirmed');
    const atHome = confirmed.filter(s => s.start_date <= today && s.end_date >= today);
    const arriving = confirmed.filter(s => s.start_date === today);
    const leaving = confirmed.filter(s => s.end_date === today);
    const meetGreets = api.stays.filter(s => s.status === 'meet_greet' && s.start_date === today);
    $('opsBusinessTitle').textContent = business?.name || 'Your business';
    $('opsTodayDate').textContent = new Intl.DateTimeFormat('en-AU', { weekday:'long', day:'numeric', month:'long', year:'numeric' }).format(new Date());
    $('opsTenantMeta').textContent = `${business?.timezone || 'Australia/Sydney'} · tenant ${safeText(business?.id).slice(0,8)}…`;
    $('opsAtHome').textContent = atHome.length; $('opsArriving').textContent = arriving.length; $('opsLeaving').textContent = leaving.length; $('opsMeetGreets').textContent = meetGreets.length;
    const capacity = Number(business?.normal_capacity || 0); $('opsCapacity').textContent = `${atHome.length}/${capacity}`;
    const remaining = Math.max(0, capacity - atHome.length), banner = $('opsCapacityBanner');
    if (capacity && atHome.length >= capacity) { banner.dataset.state = 'full'; banner.textContent = `Capacity reached · ${atHome.length} of ${capacity} dogs in care today.`; }
    else if (capacity && remaining <= 1) { banner.dataset.state = 'warn'; banner.textContent = `${remaining} place remaining · ${atHome.length} of ${capacity} dogs in care today.`; }
    else { banner.dataset.state = 'ok'; banner.textContent = `${remaining} places available · ${atHome.length} of ${capacity} dogs in care today.`; }

    $('opsAtHomeEmpty').hidden = atHome.length > 0; atHome.forEach(stay => $('opsAtHomeList').appendChild(miniCard(stay, `${humanDate(stay.start_date)} → ${humanDate(stay.end_date)}`)));
    const movements = [...arriving.map(stay => ({ stay, label:'Arriving', time:stay.arrival_time })), ...leaving.map(stay => ({ stay, label:'Leaving', time:stay.departure_time }))].sort((a,b) => safeText(a.time).localeCompare(safeText(b.time)));
    $('opsMovesEmpty').hidden = movements.length > 0; movements.forEach(row => $('opsMovesList').appendChild(miniCard(row.stay, `${row.label}${row.time ? ` · ${humanTime(row.time)}` : ''}`)));
    $('opsMeetEmpty').hidden = meetGreets.length > 0; meetGreets.forEach(stay => $('opsMeetList').appendChild(miniCard(stay, `Meet & Greet${stay.arrival_time ? ` · ${humanTime(stay.arrival_time)}` : ''}`)));
  }

  function renderCalendar(host) {
    host.innerHTML = `<section class="panel ops-calendar"><div class="ops-calendar-toolbar"><div><p class="eyebrow">Calendar</p><h2 id="opsMonthLabel"></h2></div><div class="button-row"><button class="ghost" type="button" data-cal="prev">←</button><button class="secondary" type="button" data-cal="today">Today</button><button class="ghost" type="button" data-cal="next">→</button><button type="button" data-ops-jump="add">+ Add booking</button></div></div><div class="ops-weekdays"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div id="opsCalendarGrid" class="ops-calendar-grid"></div><div class="ops-legend"><span class="confirmed">Confirmed</span><span class="potential">Potential</span><span class="meet_greet">Meet & Greet</span><span class="completed">Completed</span></div></section>`;
    const cursor = api.calendarCursor, year = cursor.getFullYear(), month = cursor.getMonth(), today = isoToday();
    $('opsMonthLabel').textContent = new Intl.DateTimeFormat('en-AU', { month:'long', year:'numeric' }).format(cursor);
    const first = new Date(year, month, 1), mondayOffset = (first.getDay()+6)%7, gridStart = new Date(year, month, 1-mondayOffset), grid = $('opsCalendarGrid');
    for (let i=0;i<42;i++) {
      const d = new Date(gridStart); d.setDate(gridStart.getDate()+i);
      const key = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
      const cell = document.createElement('div'); cell.className = 'ops-calendar-day'; if (d.getMonth()!==month) cell.classList.add('is-other'); if (key===today) cell.classList.add('is-today');
      const head = document.createElement('div'); head.className='ops-calendar-date'; const num=document.createElement('span'); num.textContent=d.getDate(); const cap=document.createElement('small');
      const occupancy=api.stays.filter(s=>s.status==='confirmed'&&s.start_date<=key&&s.end_date>=key).length; cap.textContent=occupancy?`${occupancy}/${activeBusiness()?.normal_capacity||0}`:''; head.append(num,cap); cell.appendChild(head);
      const events=document.createElement('div'); events.className='ops-calendar-events';
      const dayStays=api.stays.filter(s=>s.status!=='cancelled'&&(s.status==='meet_greet'?s.start_date===key:s.start_date<=key&&s.end_date>=key));
      dayStays.slice(0,4).forEach(stay=>{const dog=dogById(stay.dog_id),btn=document.createElement('button');btn.type='button';btn.className=`ops-calendar-event ${stay.status}`;btn.textContent=`${stay.status==='meet_greet'?'M&G · ':''}${dog?.dog_name||'Dog'}`;btn.dataset.editStay=stay.id;events.appendChild(btn);});
      if(dayStays.length>4){const more=document.createElement('small');more.textContent=`+${dayStays.length-4} more`;events.appendChild(more);} cell.appendChild(events);grid.appendChild(cell);
    }
  }

  function renderAdd(host) {
    const isEdit = Boolean(api.editingStayId), stay = isEdit ? api.stays.find(s=>s.id===api.editingStayId) : null, defaults=activeSettings(), today=isoToday();
    host.innerHTML = `<section class="panel"><div class="split-heading"><div><p class="eyebrow">Booking</p><h2>${isEdit?'Edit booking':'Add a booking'}</h2><p class="muted">Confirmed stays, potential stays and Meet & Greets are tenant-scoped.</p></div><span class="pill soft">${isEdit?'EDIT':'NEW'}</span></div><form id="opsBookingForm" class="grid-form"><label class="full">Dog<select id="opsDogSelect" required></select></label><div id="opsNewDog" class="full ops-nested" hidden><p class="eyebrow">New client dog</p><div class="grid-form"><label>Dog name<input id="opsNewDogName"></label><label>Breed<input id="opsNewBreed"></label><label>Owner name<input id="opsOwnerName"></label><label>Owner phone<input id="opsOwnerPhone" type="tel"></label></div></div><label>Booking status<select id="opsStatus"><option value="confirmed">Confirmed stay</option><option value="potential">Potential stay</option><option value="meet_greet">Meet & Greet</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label>Start date<input id="opsStart" type="date" required></label><label>End date<input id="opsEnd" type="date" required></label><label>Arrival / appointment time<input id="opsArrival" type="time"></label><label>Departure time<input id="opsDeparture" type="time"></label><label class="full">Booking notes<textarea id="opsNotes" rows="4"></textarea></label><div class="full button-row ops-booking-actions"><button type="submit">${isEdit?'Save booking':'Create booking'}</button>${isEdit?'<button type="button" class="secondary" data-cancel-edit>Cancel edit</button>':''}${isEdit&&activeMembership()?.role==='owner'?'<button type="button" class="danger" data-delete-stay>Delete booking</button>':''}</div></form><p id="opsBookingMessage" class="message" role="status"></p></section>`;
    const select=$('opsDogSelect'); const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Choose a dog';select.appendChild(placeholder);api.dogs.forEach(dog=>{const o=document.createElement('option');o.value=dog.id;o.textContent=`${dog.dog_name}${dog.breed?` · ${dog.breed}`:''}`;select.appendChild(o)});const fresh=document.createElement('option');fresh.value='__new__';fresh.textContent='+ Add a new dog';select.appendChild(fresh);
    if(stay){select.value=stay.dog_id;$('opsStatus').value=stay.status;$('opsStart').value=stay.start_date;$('opsEnd').value=stay.end_date;$('opsArrival').value=safeText(stay.arrival_time).slice(0,5);$('opsDeparture').value=safeText(stay.departure_time).slice(0,5);$('opsNotes').value=stay.notes||'';} else {$('opsStatus').value='confirmed';$('opsStart').value=today;$('opsEnd').value=today;$('opsArrival').value=safeText(defaults.default_arrival_time).slice(0,5);$('opsDeparture').value=safeText(defaults.default_departure_time).slice(0,5);}
  }

  function careBuckets(){const today=isoToday();return{current:api.stays.filter(s=>s.status==='confirmed'&&s.start_date<=today&&s.end_date>=today),future:api.stays.filter(s=>s.status==='confirmed'&&s.start_date>today),past:api.stays.filter(s=>(s.status==='confirmed'&&s.end_date<today)||s.status==='completed').sort((a,b)=>b.end_date.localeCompare(a.end_date)),clients:api.dogs};}
  function careCard(stay,bucket){const dog=dogById(stay.dog_id),card=document.createElement('article');card.className='ops-care-card';const top=document.createElement('div');top.className='ops-care-head';const text=document.createElement('div');const h=document.createElement('h3');h.textContent=dog?.dog_name||'Unknown dog';const breed=document.createElement('small');breed.textContent=dog?.breed||'Breed not added';text.append(h,breed);const chip=document.createElement('span');chip.className=`ops-status ${bucket}`;chip.textContent=bucket;top.append(text,chip);const dates=document.createElement('p');dates.textContent=`${humanDate(stay.start_date,true)} → ${humanDate(stay.end_date,true)}`;const owner=document.createElement('p');owner.textContent=`${safeText(dog?.owner_name)||'Owner not added'}${dog?.owner_phone?` · ${dog.owner_phone}`:''}`;const actions=document.createElement('div');actions.className='button-row';const profile=document.createElement('button');profile.type='button';profile.className='secondary';profile.textContent='Profile';profile.dataset.openDog=stay.dog_id;const booking=document.createElement('button');booking.type='button';booking.className='ghost';booking.textContent='Booking';booking.dataset.editStay=stay.id;actions.append(profile,booking);card.append(top,dates,owner,actions);return card;}
  function clientCard(dog){const card=document.createElement('article');card.className='ops-care-card';const h=document.createElement('h3');h.textContent=dog.dog_name;const breed=document.createElement('small');breed.textContent=dog.breed||'Breed not added';const owner=document.createElement('p');owner.textContent=dog.owner_name||'Owner not added';const count=document.createElement('p');const n=api.stays.filter(s=>s.dog_id===dog.id&&s.status!=='cancelled').length;count.textContent=`${n} booking${n===1?'':'s'}`;const button=document.createElement('button');button.type='button';button.textContent='Open profile';button.dataset.openDog=dog.id;card.append(h,breed,owner,count,button);return card;}

  function renderCare(host) {
    const buckets=careBuckets(), rows=buckets[api.careTab]||[];
    host.innerHTML=`<section class="panel"><div class="split-heading"><div><p class="eyebrow">Care</p><h2>Guest care</h2><p class="muted">Current, future and historical stays for this business only.</p></div><button type="button" data-ops-jump="add">+ Add booking</button></div><div class="ops-care-tabs"><button data-care="current">Current <span>${buckets.current.length}</span></button><button data-care="future">Future <span>${buckets.future.length}</span></button><button data-care="past">Past <span>${buckets.past.length}</span></button><button data-care="clients">Clients <span>${buckets.clients.length}</span></button></div><div id="opsCareEmpty" class="empty-state"><span class="empty-icon">🐶</span><strong>No records in this view</strong><p>Add or confirm a booking to populate Care.</p></div><div id="opsCareGrid" class="ops-care-grid"></div></section><section id="opsProfilePanel" class="panel" hidden></section>`;
    document.querySelectorAll('[data-care]').forEach(b=>b.classList.toggle('is-active',b.dataset.care===api.careTab));$('opsCareEmpty').hidden=rows.length>0;rows.forEach(row=>$('opsCareGrid').appendChild(api.careTab==='clients'?clientCard(row):careCard(row,api.careTab)));
  }

  function renderProfile(dogId){const dog=dogById(dogId),panel=$('opsProfilePanel');if(!dog||!panel)return;panel.hidden=false;panel.innerHTML=`<div class="split-heading"><div><p class="eyebrow">Dog profile</p><h2 id="opsProfileTitle"></h2></div><button class="ghost" type="button" data-close-profile>Close</button></div><form id="opsProfileForm" class="grid-form"><label>Dog name<input id="opsProfileName" required></label><label>Breed<input id="opsProfileBreed"></label><label>Owner name<input id="opsProfileOwner"></label><label>Owner phone<input id="opsProfilePhone"></label><label class="full">Care notes<textarea id="opsProfileNotes" rows="4"></textarea></label><div class="full button-row"><button type="submit">Save profile</button></div></form><div class="ops-history"><p class="eyebrow">Stay history</p><div id="opsHistoryList" class="ops-card-list"></div></div><p id="opsProfileMessage" class="message"></p>`;$('opsProfileTitle').textContent=dog.dog_name;$('opsProfileName').value=dog.dog_name||'';$('opsProfileBreed').value=dog.breed||'';$('opsProfileOwner').value=dog.owner_name||'';$('opsProfilePhone').value=dog.owner_phone||'';$('opsProfileNotes').value=dog.notes||'';panel.dataset.dogId=dog.id;const history=api.stays.filter(s=>s.dog_id===dog.id).sort((a,b)=>b.start_date.localeCompare(a.start_date));history.forEach(stay=>$('opsHistoryList').appendChild(miniCard(stay,`${statusLabel(stay.status)} · ${humanDate(stay.start_date)} → ${humanDate(stay.end_date)}`)));if(!history.length){const p=document.createElement('p');p.className='muted';p.textContent='No stay history yet.';$('opsHistoryList').appendChild(p);}panel.scrollIntoView({behavior:'smooth',block:'start'});}

  function renderSettings(host){const business=activeBusiness(),s=activeSettings();host.innerHTML=`<section class="panel"><div class="split-heading"><div><p class="eyebrow">Business settings</p><h2>Workspace configuration</h2></div><span class="pill soft">Owner controlled</span></div><form id="opsSettingsForm" class="grid-form"><label>Business name<input id="opsSettingsName" required></label><label>Timezone<input id="opsSettingsTimezone" required></label><label>Normal capacity<input id="opsSettingsCapacity" type="number" min="1" max="100" required></label><label>Contact name<input id="opsSettingsContact"></label><label>Contact email<input id="opsSettingsEmail" type="email"></label><label>Contact phone<input id="opsSettingsPhone"></label><label>Default arrival time<input id="opsSettingsArrival" type="time"></label><label>Default departure time<input id="opsSettingsDeparture" type="time"></label><label class="full">Address<textarea id="opsSettingsAddress" rows="3"></textarea></label><div class="full button-row"><button type="submit">Save business settings</button></div></form><p id="opsSettingsMessage" class="message"></p></section>`;$('opsSettingsName').value=business?.name||'';$('opsSettingsTimezone').value=business?.timezone||'Australia/Sydney';$('opsSettingsCapacity').value=business?.normal_capacity||4;$('opsSettingsContact').value=s.contact_name||'';$('opsSettingsEmail').value=s.contact_email||'';$('opsSettingsPhone').value=s.contact_phone||'';$('opsSettingsArrival').value=safeText(s.default_arrival_time).slice(0,5);$('opsSettingsDeparture').value=safeText(s.default_departure_time).slice(0,5);$('opsSettingsAddress').value=s.address_text||'';if(activeMembership()?.role!=='owner')$('opsSettingsForm').querySelectorAll('input,textarea,button').forEach(n=>n.disabled=true);}

  function renderView(view){api.view=view;document.querySelectorAll('[data-ops-view]').forEach(b=>b.classList.toggle('is-active',b.dataset.opsView===view));const host=$('opsViewHost');host.replaceChildren();if(view==='today')renderToday(host);else if(view==='calendar')renderCalendar(host);else if(view==='add')renderAdd(host);else if(view==='care')renderCare(host);else renderSettings(host);window.WaffleRndOpsActions?.bindView();}

  window.WaffleRndOpsRender={renderView,renderProfile};
})();
